version: "3.9"

services:
    veloce:
        container_name: veloce
        image: veloce
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        expose:
            - "${PORT}"